---
title: "Supplementary material for:\nWhen do we need multiple infectious disease models? Agreement between projection rank and magnitude in a multi-model setting"
author: 
  - La Keisha Wade-Malone, The Pennsylvania State University
  - Emily Howerton, The Pennsylvania State University
  - William J.M. Probert, University of Oxford
  - Michael C. Runge, U.S. Geological Survey
  - Cecile Viboud, National Institutes of Health
  - Katriona Shea, The Pennsylvania State University
output: pdf_document
header-includes:
  - \usepackage{caption}
  - \DeclareCaptionLabelFormat{nospace}{#1#2}
  - \captionsetup[figure]{labelformat=nospace}
  - \captionsetup[table]{labelformat=nospace}
---

\def\figurename{Fig. S}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, cache = TRUE)

library(deSolve)
library(dplyr)
library(data.table)
library(ggplot2)
library(scales)
library(cowplot)
library(reshape2)
library(metR)
library(RColorBrewer)

eval_repo_path <- "~/Documents/GitHub/covid19-scenario-hub_evaluation"
data_repo_path <- file.path(paste(eval_repo_path), "data-raw/")

# location information
locations <- read.csv(file.path(paste0(data_repo_path, "data-locations/locations.csv")))
# remove territories
locations <- setDT(locations)[!(location %in% c("60", "66", "69", "72", "74", "78"))]

# plotting objects
source("code/manuscript-figures/plotting-utils.R")

# base text size
sz = 9
```


```{r fig-s1, fig.cap="Susceptible-Infected-Recovered (SIR) dynamics of infected individuals for varying transmission rate (beta) and recovery rate (gamma) parameters. Dynamics are shown for three scenarios: no intervention (solid line), non-pharmaceutical interventions (NPIs) that reduce transmission by 30% (short dashed line), and vaccination of approximately 1% of the susceptible population per day (long dashed line). Data from SIR model simulations.", fig.height = 5}
source("code/SIR-simulations/functions.R")
source("code/SIR-simulations/setup_model.R")

test_runs = expand.grid(N=1000,
                        beta =seq(.75,1.25,by=0.1),
                        gamma = seq(.1, 0.5, by=0.1),
                        V=c(0,pick_v), # vaccination level
                        d=c(0,pick_d)) # distancing intensity)
test_runs$id = 1:nrow(test_runs)

dynam <- list()
for(row in 1:nrow(test_runs)){
  dynam[[row]] = ode(y=start, times=times, func = sirmod, parms = test_runs[row,])
  dynam[[row]] = as.data.frame(dynam[[row]])
}
dynam <- rbindlist(dynam, idcol = "id") %>%
  .[test_runs, on = .(id)]

#### PLOT VARIOUS TRAJECTORIES -------------------------------------------------
dynam %>% 
  .[V*d == 0] %>%
  .[, intervention_id := ifelse(V == 0 & d == 0, "no intervention", 
                                ifelse(V > 0, "vaccination", "NPIs"))] %>%
ggplot(aes(x = time, y = I, linetype = intervention_id)) + 
  geom_line() + 
  facet_grid(cols = vars(beta), rows = vars(gamma), 
             labeller = label_both) + 
  labs(y = "infected individuals") + 
  theme_bw(base_size = sz) + 
  theme(legend.position = "bottom", 
        legend.title = element_blank(), 
        panel.grid = element_blank(), 
        strip.background = element_blank())
# ggsave("figures/figureS1.pdf", width = 8.5, height = 7)
```

```{r fig-s2, fig.height=6, fig.cap = "Results from Fig. 1B repeated for varying intervention efficacies (vaccination rate ranging from 0.5% to 2% of the population per day, and NPI reduction of the transmission rate ranging from 10% to 40%). Each panel shows a large part of the space of possible models across biological uncertainties (transmission rate, $\\beta$, and recovery rate, $\\gamma$). Each position on the graph represents an individual model, the color of the tile represents the recommended intervention (orange: non-pharmaceutical interventions, NPIs; purple: vaccination), and the intensity of the color is the magnitude of the projected difference in cumulative infections. Colors have been rescaled from Fig. 1. The gray line shows where the difference in cumulative infections is 0, or where neither intervention is recommended over the other. Black contours show sample values of individual model $R_0$ = 2,3.5, 6, and 10. Data from SIR model simulations."}
multi_panel <- read.csv("output-data/SIR-simulations/SIR_varying_intervention_params.csv")

multi_panel_alt <- multi_panel %>%
  select(beta, gamma, cases, v_rate, d_rate, peak_cases, intervention) %>%
  reshape2::melt(c("beta", "gamma", "v_rate", "d_rate", "intervention")) %>%
  reshape2::dcast(beta + gamma + v_rate + d_rate + variable ~ intervention, 
                  value.var = "value") %>%
  mutate(diff = (v - d),
         rel_diff = (v-d)/n,
         rec = ifelse(diff < 0, "vaccination", "distancing"))

m_case <- multi_panel_alt %>%
  filter(variable == "cases") %>%
  mutate(diff = abs(diff)) %>%
  pull(diff) %>% max()

multi_panel_alt  %>%
  filter(variable == "cases") %>%
  ggplot(aes(x = beta, y = gamma)) +
  geom_tile(aes(fill = diff)) +
  geom_contour(aes(z = diff), breaks = 0, color = "grey") +
  geom_contour(aes(z = beta/gamma),
               color = "black",
               breaks = c(2,3.5,6,10)) +
  geom_text_contour(aes(z = beta/gamma),
                    color = "black",
                    breaks = c(2,2.5,3.5,5,6,7,10),
                    stroke  = 0.2) +
  facet_grid(cols = vars(v_rate), rows = vars(d_rate), 
             labeller = labeller(v_rate = labs_v, 
                                 d_rate = labs_d)) +
  scale_x_continuous(expand = c(0,0), name = "transmission rate") +
  scale_y_continuous(expand = c(0,0), name = "recovery rate") +
  scale_fill_distiller(palette = "PuOr",
                       limits= c(-1,1)*m_case,
                       name = "difference in\ncumulative\ninfections",
                       breaks = seq(-500,500, 250),
                       labels = c("-500\nvaccination", "-250", "0", "250", "500\nNPIs")) +
  theme_bw(base_size = sz) +
  theme(legend.position = "bottom",
        legend.key.width = unit(0.6, "in"), 
        strip.background = element_blank())
```

```{r fig-s3, fig.height=6, fig.cap = "Model results for minimizing peak infections. Results are shown for varying intervention efficacies (vaccination rate ranging from 0.5% to 2% of the population per day, and NPI reduction of the transmission rate ranging from 10% to 40%). Each panel shows a large part of the space of possible models across biological uncertainties (transmission rate, $\\beta$, and recovery rate, $\\gamma$). Each position on the graph represents an individual model, the color of the tile represents the recommended intervention (orange: non-pharmaceutical interventions, NPIs; purple: vaccination), and the intensity of the color is the magnitude of the projected difference in peak infections. Colors have been rescaled from Figure 1. The gray line shows where the difference in peak infections is 0, or where neither intervention is recommended over the other. Black contours show sample values of individual model $R_0$ = 2,3.5, 6, and 10. Data from SIR model simulations."}
multi_panel_alt <- multi_panel %>%
  select(beta, gamma, cases, v_rate, d_rate, peak_cases, intervention) %>%
  reshape2::melt(c("beta", "gamma", "v_rate", "d_rate", "intervention")) %>%
  reshape2::dcast(beta + gamma + v_rate + d_rate + variable ~ intervention, 
                  value.var = "value") %>%
  mutate(diff = (v - d),
         rel_diff = (v-d)/n,
         rec = ifelse(diff < 0, "vaccination", "distancing"))

m_peak <- multi_panel_alt %>%
  filter(variable == "peak_cases") %>%
  mutate(diff = abs(diff)) %>%
  pull(diff) %>% max()

multi_panel_alt  %>%
  filter(variable == "peak_cases") %>%
  ggplot(aes(x = beta, y = gamma)) +
  geom_tile(aes(fill = diff)) +
  geom_contour(aes(z = beta/gamma),
               color = "black",
               breaks = c(2,3.5,6,10)) +
  geom_text_contour(aes(z = beta/gamma),
                    color = "black",
                    breaks = c(2,2.5,3.5,5,6,7,10),
                    stroke  = 0.2) +
  facet_grid(cols = vars(v_rate), rows = vars(d_rate), 
             labeller = labeller(v_rate = labs_v, 
                                 d_rate = labs_d)) +
  scale_x_continuous(expand = c(0,0), name = "transmission rate") +
  scale_y_continuous(expand = c(0,0), name = "recovery rate") +
  scale_fill_distiller(palette = "PuOr",
                       limits= c(-1,1)*m_peak,
                       name = "difference in\npeak\ninfections",
                       breaks = seq(-150,150, 75),
                       labels = c("-150\nvaccination", "-75", "0", "75", "150\nNPIs")) +
  theme_bw(base_size = sz) +
  theme(legend.position = "bottom",
        legend.key.width = unit(0.6, "in"), 
        strip.background = element_blank())
```

```{r fig-s4, fig.height=6, fig.cap = "Probability of models agreeing about intervention scenario ranking or estimates of cumulative infections without intervention for different sampling schemes (columns) and number of models agreeing (rows). Probabilities are calculated for a set of models of size two to size twelve, either when choosing randomly among all models or among models with “similar” assumptions, defined as those with transmission and recovery rate assumptions within $\\pm$ 0.1, $\\pm$ 0.05 or $\\pm$ 0.15 of a given model. Agreement probability of at least 2, 4, 6, or 8 models is shown for estimates of cumulative cases within 20 infections (2% of population, red), within 50 infections (5% of population, yellow), within 100 infections (10% of population, blue), or intervention scenario ranking (black). Data from SIR model simulations."}
samp <- read.csv("output-data/SIR-simulations/SIR_sample_model_sets.csv")
setDT(samp)

# summarize
plt_data <- merge(setDT(expand.grid(s = 2:12, 
                                    variable = unique(samp$variable),
                                    mod_type = unique(samp$mod_type),
                                    value = 2:12)) %>% 
                    .[value <= s], 
                  samp %>% 
                    .[, .(n = .N), by = .(s, variable, v, mod_type, value)] %>%
                    .[, p := n/sum(n), by = .(s, variable, v, mod_type)], 
                  by = c("s", "variable", "mod_type", "value"), all = TRUE) %>% 
  .[!(variable %in% c("kw", "kw2", "icc"))] %>%
  .[, p := ifelse(is.na(p), 0, p)] %>%
  .[order(-value),] %>%
  .[, ncum := cumsum(p), by = .(s, variable, mod_type)] %>%
  .[value != 1]
plt_data <- plt_data[, c("variable_type", "variable_tol") := data.table(stringr::str_split_fixed(plt_data$variable, "_", 2))]

ggplot(data = plt_data[value %in% seq(2,8,2) & 
                         variable %in% c(paste0("mag_abs_",sim_abs_levels),"rec")], 
       aes(x = s)) +  #, y = value0
  geom_line(aes(y = ncum, color = as.factor(variable)), 
            size = 0.25, alpha = 0.7) +
  geom_point(aes(y = ncum, color = as.factor(variable)), size = 1.5) +
  # geom_tile(aes(fill = ncum)) + 
  # geom_tile(data = plt_data[ncum == 1], aes(fill = ncum), color = "white", size =1) + 
  #geom_contour(aes(z = ncum), breaks = c(0.5, 0.25, 0.75, 0.9)) +
  facet_grid(rows = vars(as.factor(paste0("at least ", value, " models agree"))), 
             cols = vars(mod_type),
             labeller = labeller(mod_type = mod_type_labs),
             switch = "y") +
  guides(color = guide_legend(nrow = 2)) +
  scale_color_manual(# breaks = c(0,10,25,50,100),
    labels = c(paste0("Estimates agree within ", sim_abs_levels, " cases"),
               "Intervention scenario ranking agrees"),
    values = c(brewer.pal(4, "RdYlBu")[1:3], "black")) +
  #name = "number of models making predictions") + 
  scale_x_continuous(name = "number of models in set") +
  scale_y_continuous(labels = percent, 
                     name = "probability") + 
  theme_bw(base_size = sz) + 
  theme(#axis.title.y = element_blank(), 
    legend.position = "bottom", 
    legend.title = element_blank(),
    panel.grid.major.x = element_blank(), 
    panel.grid.minor = element_blank(), 
    strip.background = element_blank(), 
    strip.placement = "outside")#, strip.text = element_text(hjust = 0)
```

```{r fig-s5, fig.height=7, fig.cap = "Probability of models agreeing about intervention scenario ranking or estimates of cumulative infections without intervention (columns) for different degrees of model similarity (rows). Probabilities are calculated for a set of models of size two to size twelve, either when choosing randomly among all models or among models with “similar” assumptions, defined as those with transmission and recovery rate assumptions within $\\pm$ 0.1, $\\pm$ 0.05 or $\\pm$ 0.15 of a given model. Agreement probability of at least 2, 4, 6, or 8 models is shown for estimates of cumulative cases within 20 infections (2% of population), within 50 infections (5% of population), within 100 infections (10% of population), or intervention scenario ranking. Breakpoints where agreement probability is at least 0.5 is shown with a solid black line and agreement probability is at least 0.9 is shown with a dashed black line. Data from SIR model simulations."}
# create data.frames to draw lines on heatmap at 50% 
stps_50pct <- plt_data %>%
  .[variable %in% c(paste0("mag_abs_", sim_abs_levels), "rec")] %>%
  .[, less_50pct_flag := ifelse(ncum < 0.5, 1, 0)] %>%
  .[less_50pct_flag == 1] %>%
  .[, .(min_less_50 = min(value)), by = .(s, mod_type, variable)] 
# add one extra segment to finish line at s = 12
stps_50pct <- rbindlist(list(
  stps_50pct, 
  stps_50pct[s == 12] %>% 
    .[, s := s+1]))

# repeat for 90%
stps_90pct <- plt_data %>%
  .[variable %in% c(paste0("mag_abs_", sim_abs_levels), "rec")] %>%
  .[, less_90pct_flag := ifelse(ncum < 0.9, 1, 0)] %>%
  .[less_90pct_flag == 1] %>%
  .[, .(min_less_90 = min(value)), by = .(s, mod_type, variable)]
# add one extra segment to finish line at s = 12
stps_90pct <- rbindlist(list(
  stps_90pct, 
  stps_90pct[s == 12] %>% 
    .[, s := s+1]))


plt_data %>%
  .[variable %in% c(paste0("mag_abs_", sim_abs_levels), "rec")] %>%
  ggplot(aes(x = s, y = value)) +
  geom_tile(aes(fill = ncum)) + 
  geom_step(data = stps_50pct, 
            aes(x = s-0.5, 
                y = min_less_50-0.5), 
            linetype = "solid", 
            size = 0.7) +
  geom_step(data = stps_90pct, 
            aes(x = s-0.5,
                y = min_less_90-0.5), 
            linetype = "dashed", 
            size = 0.7) +
  facet_grid(cols = vars(variable), 
             rows = vars(mod_type), 
             labeller = labeller(variable = est_labs, 
                                 mod_type = mod_type_labs)) + 
  scale_fill_viridis_c(name = "probability of agreement") + 
  scale_linetype_manual(values = c("solid","dashed")) +
  scale_x_continuous(breaks = 2:12, 
                     expand = c(0,0), 
                     name = "number of models in set") +
  scale_y_continuous(breaks = 2:12, 
                     expand = c(0,0), 
                     name = "number of models agreeing") + 
  theme_bw(base_size = sz) + 
  theme(legend.key.width = unit(1,"cm"),
        legend.position = "bottom", 
        panel.grid = element_blank(), 
        strip.background = element_blank())
```

```{r fig-s6, fig.height=3, fig.cap = " (A) Probability of at least 66% of models agreeing for a relative definition of agreement. Here, agreement probability for projection magnitude is calculated relative to the projection size, i.e., agreement consitutes the maximum number of estimates from a set with cumulative cases falling within a window of 2% of the projected magnitude (red), within 5% of the projected magnitude (yellow), within 10% of the projected magnitude (light blue), or within 15% of the projected magnitude (dark blue). Agreement about recommended intervention is shown for reference (black). Probabilities are calculated for agreement of 2 models out of a set of 3, 4 out of a set of 6, 6 out of set of 8, and 8 out of a set of 12. All probabilities were calculated both when choosing randomly among all models or among models with “similar” assumptions. Similar models are defined as those with transmission and recovery rate assumptions within ±0.1 of a given model. (B) The size of the window within which cumulative case estimates are considered to agree, for 2% of the projected magnitude (red),5% (yellow), 10% (light blue), or 15% (dark blue). The points show the average across all randomly drawn sets of models, and the ribbon show the 25th and 75th quantiles of this distribution. Data from SIR model simulations."}
p1 <- ggplot(data = plt_data %>%
         .[, rel_value := value/s] %>%
         .[rel_value == 2/3 & mod_type %in% c("all", "similar") & 
             variable %in% c(paste0("mag_rel_", sim_rel_levels), "rec")],
       aes(x = s)) +  #, y = value0
  geom_line(aes(y = ncum, color = as.factor(variable)), 
            linewidth = 0.25, alpha = 0.7) +
  geom_point(aes(y = ncum, color = as.factor(variable)), size = 1.5) +
  facet_grid(cols = vars(paste(mod_type, "models"))) +
  guides(color = guide_legend(nrow = 2)) +
  scale_color_manual(labels = c(paste0("Estimates agree within ", sim_rel_levels*100, "%"),
                                "Intervention scenario ranking agrees"),
                     values = c(brewer.pal(4, "RdYlBu"), "black")) +
  scale_x_continuous(breaks = seq(3,12,3), 
                     name = "number of models in set") +
  scale_y_continuous(expand = c(0,0), 
                     labels = percent, 
                     limits = c(0,1),
                     name = "probability at least\n66% of models agree") + 
  theme_bw(base_size = sz) + 
  theme(
    legend.position = "bottom", 
    legend.title = element_blank(),
    panel.grid.major.x = element_blank(), 
    panel.grid.minor = element_blank(), 
    strip.background = element_blank(), 
    strip.placement = "outside")
  
p2 <- ggplot(data = plt_data %>%
         .[substr(variable,1,3) == "win"] %>%
         .[, .(m = mean(value), 
               md = median(value), 
               lwr = quantile(value, 0.25), 
               upr = quantile(value, 0.75)), by = .(s, variable)], 
       aes(x = s)) + 
  geom_ribbon(aes(ymin = lwr, ymax = upr, fill = variable), alpha = 0.2) +
  geom_point(aes(y = md, color = variable)) + 
  geom_line(aes(y = md, color = variable)) +
  facet_wrap(vars(""), ncol = 1) +
  scale_color_manual(values = c(brewer.pal(4, "RdYlBu"))) +
  scale_fill_manual(values = c(brewer.pal(4, "RdYlBu"))) +
  scale_x_continuous(breaks = seq(3,12,3), 
                     name = "number of models in set") +
  scale_y_continuous(name = "window size") + 
  theme_bw(base_size = sz) + 
  theme(legend.position = "none", 
        strip.background = element_blank())

l <- get_legend(p1)

plot_grid(
  plot_grid(p1 + theme(legend.position = "none"), p2, nrow = 1, labels = LETTERS[1:2], rel_widths = c(0.6, 0.3)), 
  l, ncol = 1, rel_heights = c(0.85,0.15))
```

```{r fig-s7, fig.height=2.5, fig.cap = "Results from Fig. 3 replicated with agreement assessed for only two intervention scenarios. For a varying number of models in a set, agreement is measured for projection magnitude across intervention scenarios (using intraclass correlation coefficient, ICC) and ranking of intervention scenarios (using Kendall’s W). Results are shown when models in the set come from all possible models considered (red), and when models are similar (blue). Each point represents one set of randomly selected models from either all possible models considered (red) or a neighborhood of “similar” models (blue, those with transmission and recovery rate assumptions within ±0.1 of a given model). Ellipses show the area within which 95% of points fall. Dotted horizontal lines show agreement that is significant with a p-value of 0.05. Data from SIR model simulations."}
n = 2
kw_sig = data.frame(s = 2:10)
kw_sig$p_0.05 = qchisq(0.05, df = n-1, lower.tail = FALSE)/(kw_sig$s*(n-1))
setDT(kw_sig)

samp %>% 
  .[variable %in% c("kw2", "icc") & 
      mod_type %in% c("all", "similar") &
      it %in% sample(max(samp$it), 1000)] %>% # randomly select 1000 to plot for efficiency
  data.table::dcast(it + id + mod_type + s ~ variable, value.var = "value") %>%
  .[s %in% c(4,6,8,10)] %>%
  ggplot(aes(x = icc, y = kw2, color = mod_type)) +
  geom_point(alpha = 0.05) + 
  geom_hline(data = kw_sig %>%
               .[s %in% c(4,6,8,10)], 
             aes(yintercept = p_0.05), linetype = "dotted") +
  stat_ellipse() +
  facet_grid(cols = vars(s), 
             labeller = labeller(s = mod_labs))+#, rows = vars(mod_type)) + 
  scale_color_brewer(labels = c("all models", "similar models"), 
                     palette = "Set1") +
  scale_x_continuous(breaks = c(0,0.5,1),
                     limits = c(0,1), 
                     name = "agreement between values\n(intraclass correlation coefficient)")+
  scale_y_continuous(breaks = c(0,0.5,1),
                     limits = c(0,1), 
                     name = "agreement between ranks\n(Kendall's W)") + 
  theme_bw(base_size = sz) + 
  theme(legend.margin = margin(rep(0,4)),
        legend.position = "bottom",
        legend.title = element_blank(),
        panel.grid = element_blank(),
        strip.background = element_blank(), 
        strip.placement = "outside")
```

```{r generate-fig-s7-21}
p <- setDT(read.csv("output-data/SMH-analysis/SMH_ranks.csv"))
plt_list <- list()
plt_cap <- list()
counter <- 1
rounds <- c(1:7,9,11:16)
for(i in 1:length(rounds)){
  rnd_i = rounds[i]
  plt_list[[counter]] <- p[target == "cum hosp" & 
                             round == rnd_i &
                             quantile == 0.5 &
                             horiz == max_horiz] %>%
    .[, n_mods := length(unique(model_name)), by = .(location)] %>%
    ggplot() + 
    geom_point(aes(x = value/population*1E5, 
                   y = paste0(scenario_letter, model_name), 
                   color = as.factor(r)), 
               size = 0.7) +
    geom_hline(aes(yintercept = n_mods + 0.5)) +
    geom_hline(aes(yintercept = 2*n_mods + 0.5)) +
    geom_hline(aes(yintercept = 3*n_mods + 0.5)) +
    geom_hline(aes(yintercept = 4*n_mods + 0.5)) +
    ggtitle(paste0("Round ", rnd_i, " (horizon: ", max(p[round == rnd_i,"horiz"]), " weeks)")) +
    facet_wrap(vars(location_name), scales = "free_y") + #, scales = "free"
    scale_color_manual(breaks = seq(1, 4, 0.5), 
                       values = rev(brewer.pal(11,"RdYlBu")[c(2:4,5,8:10)]), 
                       name = "rank", 
                       labels = c("best", rep("", 5), "worst")) +
    scale_x_continuous(label = comma, 
                       name = "cum hosp per 100,000 population") +
    theme_bw(base_size = sz-1) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.text.y = element_blank(),
          axis.ticks.y = element_blank(),
          axis.title.y = element_blank(),
          legend.position = "none",
          panel.grid.minor = element_blank(), 
          panel.spacing = unit(0, "lines"),
          strip.background = element_blank())
  n_mods <- median(p[target == "cum hosp" & 
                       round == rnd_i &
                       horiz == max_horiz] %>%
                     .[, n_mods := length(unique(model_name)), by = .(location)] %>% 
                     pull(n_mods))
  plt_cap[[i]] <- paste0("COVID-19 Scenario Modeling Hub projections of cumulative hospitalizations for Round ",
                         rnd_i, ". Projections are collected from ", n_mods, 
                         " models for four scenarios. Across locations (panels), projections are shown for each scenario 
                           (separated by horizontal black lines) from each model (individual points), points are colored 
                           based on the rank of that scenario for each model (blue is lowest projection, and red 
                           is highest projection). Data from https://github.com/midas-network/covid19-scenario-hub_evaluation,
                           https://zenodo.org/record/8415147.")
  counter <- counter + 1
}
```

```{r fig-s7-21, fig.height = 8, fig.cap = plt_cap, results="asis"}
for(i in plt_list){
  print(
      i
    )
    cat('\n\n') 
}    
```

```{r fig-s22, fig.height = 4.5, fig.cap = "Agreement of SMH projections across rounds (panel columns) and scenarios (panel rows).  A single panel shows the maximum number of models that agree on different metrics, including agreeing about the rank of a particular scenario, and agreeing about the magnitude of the projection within a particular tolerance window. The tolerance window is defined based on a hospitalization per 100,000 population size for each location. The maximum number of agreeing models is summarized across locations, and the height of the bar shows the number of locations with a particular maximum number of agreeing models. Because a different number of modeling teams submitted to each round, the maximum agreement value on the xaxis varies. Data from agreement analysis of SMH projections."}
SMH_agreement_tolerance_method <- setDT(read.csv("output-data/SMH-analysis/SMH_agreement_tolerance_method.csv"))

SMH_agreement_tolerance_method %>% 
  data.table::melt(c("round", "target", "target_end_date", "horiz", 
                     "location", "quantile", "scenario_id", "n_models")) %>%
  .[, pct_agree := value/n_models] %>%
  .[, pct_agree_bin := case_when(pct_agree < 0.25 ~ 1, 
                                 pct_agree < 0.5 ~ 2, 
                                 pct_agree < 0.75 ~ 3, 
                                 pct_agree <= 1 ~ 4)] %>%
  .[, scenario_letter := substr(scenario_id, 1,1)] %>%
  .[variable %in% c("n_agree_rec", paste0("n_agree_mag_abs_", smh_abs_levels))] %>%
  .[, value := round(value,2)] %>%
  .[, .(n = .N), by = .(round, target, scenario_letter, pct_agree_bin, variable)] %>%
  .[, variable := factor(variable, levels = c(paste0("n_agree_mag_abs_",rev(smh_abs_levels)), "n_agree_rec"))] %>%
  .[, y := as.numeric(variable)] %>%
  .[, ybar := as.numeric(y) + (n/sum(n)*0.95), by = .(round, target, variable, scenario_letter)] %>%
  .[, round_lab := factor(paste("Round", round), levels = paste("Round", c(1:7,9,11:16)))] %>%
  ggplot() + 
  geom_hline(aes(yintercept = 4)) + 
  geom_hline(aes(yintercept = 3), color = 'lightgray') + 
  geom_hline(aes(yintercept = 2), color = 'lightgray') + 
  geom_hline(aes(yintercept = 1), color = 'lightgray') + 
  geom_rect(aes(xmin = pct_agree_bin-0.5, 
                xmax = pct_agree_bin + 0.5, 
                ymin = y, ymax = ybar), color = "black", fill = "gray", linewidth = 0.35) + 
  facet_grid(cols = vars(round_lab), rows = vars(paste("Scenario", scenario_letter))) +
  labs(x = "percent of models agreeing", 
       y = "number of locations") + 
  scale_x_continuous(breaks = 1:4, 
                     labels = c("0-24%", "25-49%", "50-74%", "75-100%")) + 
  scale_y_continuous(breaks = 1:4+0.5,
                     expand = c(0,0),
                     labels = c(paste0("magnitude within\n",rev(smh_abs_levels)," hosp/100K"), "ranking"),
                     limits = c(1,5)) +
  theme_bw(base_size = bs) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        axis.ticks.y = element_blank(),
        panel.grid = element_blank(), 
        strip.background = element_blank())
```

```{r fig-s23, fig.height = 4.5, fig.cap = "Agreement of SMH projections across rounds (panel columns) and scenarios (panel rows).  A single panel shows the maximum number of models that agree on different metrics, including agreeing about the rank of a particular scenario, and agreeing about the magnitude of the projection within a particular tolerance window. The tolerance window is defined relative to the projected magnitude; Fig. S24 shows the size of each window. The maximum number of agreeing models is summarized across locations, and the height of the bar shows the number of locations with a particular maximum number of agreeing models. Because a different number of modeling teams submitted to each round, the maximum agreement value on the xaxis varies. Data from agreement analysis of SMH projections."}
SMH_agreement_tolerance_method %>% 
  data.table::melt(c("round", "target", "target_end_date", "horiz", 
                     "location", "quantile", "scenario_id", "n_models")) %>%
  .[, pct_agree := value/n_models] %>%
  .[, pct_agree_bin := case_when(pct_agree < 0.25 ~ 1, 
                                 pct_agree < 0.5 ~ 2, 
                                 pct_agree < 0.75 ~ 3, 
                                 pct_agree <= 1 ~ 4)] %>%
  .[, scenario_letter := substr(scenario_id, 1,1)] %>%
  .[variable %in% c("n_agree_rec", paste0("n_agree_mag_rel_", smh_rel_levels))] %>%
  .[, value := round(value,2)] %>%
  .[, .(n = .N), by = .(round, target, scenario_letter, pct_agree_bin, variable)] %>%
  .[, variable := factor(variable, levels = c(paste0("n_agree_mag_rel_",rev(smh_rel_levels)), "n_agree_rec"))] %>%
  .[, y := as.numeric(variable)] %>%
  .[, ybar := as.numeric(y) + (n/sum(n)*0.95), by = .(round, target, variable, scenario_letter)] %>%
  .[, round_lab := factor(paste("Round", round), levels = paste("Round", c(1:7,9,11:16)))] %>%
  ggplot() + 
  geom_hline(aes(yintercept = 4)) + 
  geom_hline(aes(yintercept = 3), color = 'lightgray') + 
  geom_hline(aes(yintercept = 2), color = 'lightgray') + 
  geom_hline(aes(yintercept = 1), color = 'lightgray') + 
  geom_rect(aes(xmin = pct_agree_bin-0.5, 
                xmax = pct_agree_bin + 0.5, 
                ymin = y, ymax = ybar), color = "black", fill = "gray", linewidth = 0.35) + 
   facet_grid(cols = vars(round_lab), rows = vars(paste("Scenario", scenario_letter))) +
  labs(x = "percent of models agreeing", 
       y = "number of locations") + 
  scale_x_continuous(breaks = 1:4, 
                     labels = c("0-24%", "25-49%", "50-74%", "75-100%")) + 
  scale_y_continuous(breaks = 1:4+0.5,
                     expand = c(0,0),
                     labels = c(paste0("magnitude\nwithin ",rev(smh_rel_levels)*100,"%"), "ranking"),
                     limits = c(1,5)) +
  theme_bw(base_size = bs) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        axis.ticks.y = element_blank(),
        panel.grid = element_blank(), 
        strip.background = element_blank())
```

```{r fig-s24, fig.cap = "The size of the window within which projections are considered to agree, for 25% of the projected magnitude, 50%, or \u00B1 75%. The points show the average across all locations, and the ribbon show the 25th and 75th quantiles of this distribution. Data from SIR model simulations. Projected cumulative hospitalizations varies by round and scenario, and hence the window size (when defined relative to the projection) also varies. Data from agreement analysis of SMH projections. "}
SMH_agreement_tolerance_method %>%
  data.table::melt(c("round", "target", "target_end_date", "horiz", "location", "quantile", "scenario_id", "n_models")) %>%
  .[locations, on = .(location)] %>%
  .[substr(variable,1,3) == "win"] %>%
  .[, scenario_letter := substr(scenario_id,1,1)] %>%
  .[, .(m = mean(value/population*1E5), 
        md = median(value/population*1E5), 
        lwr = quantile(value/population*1E5, 0.25), 
        upr = quantile(value/population*1E5, 0.75)), by = .(round, variable, scenario_letter)] %>%
  ggplot(aes(x = round)) +
  geom_ribbon(aes(ymin = lwr, ymax = upr), alpha = 0.2) +
  geom_point(aes(y = md)) + 
  geom_line(aes(y = md)) +
  facet_grid(cols = vars(paste("Scenario", scenario_letter)), 
             rows = vars(paste0(as.double(substr(as.character(variable), 12, nchar(as.character(variable))))*100,"%")), 
             scales = "free") +
  scale_y_continuous(name = "distribution of window size (per 100K population)") + 
  theme_bw(base_size = bs) + 
  theme(panel.grid.minor = element_blank(),
        strip.background = element_blank())
```

```{r null-agree-comps}
null_agreement <- setDT(read.csv("output-data/SMH-analysis/null_agreement.csv")) %>%
  .[locations, on = .(location)] %>%
  .[, target_end_date := as.IDate(target_end_date)] %>%
  .[, horiz := (target_end_date - min(target_end_date))/7 + 1, by = .(round)] %>%
  .[, max_horiz := max(horiz), by =.(round)]
SMH_agreement <- setDT(read.csv("output-data/SMH-analysis/SMH_agreement.csv")) %>%
  .[locations, on = .(location)] %>%
  .[, target_end_date := as.IDate(target_end_date)] %>%
  .[, horiz := (target_end_date - min(target_end_date))/7 + 1, by = .(round)] %>%
  .[, max_horiz := max(horiz), by =.(round)]
n_scenarios = 4
kw_sig = SMH_agreement_tolerance_method %>%
  .[locations, on = .(location)] %>%
  .[quantile == 0.5 &
        target == "cum hosp"] %>%
  .[, .(round, location_name, n_models)] %>% 
  unique() %>%
  .[, p_0.05 := qchisq(0.05, df = n_scenarios-1, lower.tail = FALSE)/(n_models*(n_scenarios-1))] %>%
  .[!(round == 3 & location_name == "Kentucky")] # a few projections were excluded from this set so do not include here either

plt_list_null <- list()
plt_cap_null <- list()
samps <- sample(1:1000, 500) # randomly select 100 samples to plot (for simiplicity)
for(i in 1:length(rounds)){
  rnd_i = rounds[i]
  pnt <- SMH_agreement  %>%
    .[horiz == max_horiz &
        quantile == 0.5 &
        round == rnd_i &
        target == "cum hosp"] 
  plt_list_null[[i]] = null_agreement %>%
    .[round == rnd_i &
        sim_id %in% samps &
        target == "cum hosp"] %>%
    ggplot() +
    geom_point(aes(x = icc_a_nonzero, y = kendall_w), alpha = 0.1, size = 0.7) +
    geom_hline(data = kw_sig[round == rnd_i], aes(yintercept = p_0.05)) + 
    geom_vline(data = pnt, aes(xintercept = icc_a_nonzero),
               color = "red", linetype = "dotted") +
    geom_hline(data = pnt, aes(yintercept = kendall_w),
               color = "red", linetype = "dotted") +
    geom_point(data = pnt, aes(x = icc_a_nonzero, y = kendall_w), color = "red") +
    ggtitle(paste0("Round ", rnd_i, " (horizon: ", max(p[round == rnd_i,"horiz"]), " weeks)")) +
    facet_wrap(vars(location_name)) +
    scale_x_continuous(breaks = c(0,1),
                       minor_breaks = c(0.5),
                       limits = c(0,1),
                       #expand = c(0,0),
                       name = "agreement between projection magnitude\n(intraclass correlation coefficient)") +
    scale_y_continuous(breaks = c(0,1),
                       minor_breaks = c(0.5),
                       limits = c(0,1),
                       #expand = c(0,0),
                       name = "agreement between scenario ranks\n(Kendall's W)") +
    theme_bw(base_size = sz-1) +
    theme(legend.position = "bottom",
          # panel.grid.minor = element_blank(),
          plot.margin = margin(c(0,0,0,0), unit = "cm"),
          strip.background = element_blank())
  plt_cap_null[[i]] <- paste0("Agreement for null model simulations and the corresponding SMH projections of cumulative hospitalizations for Round ", rnd_i, ". Agreement is calculated for projection magnitude (as measured by intraclass correlation coefficient) and scenario ranking (as measured by Kendall's W). Across locations (panels), null model results are shown with black points and SMH results are shown with a red point. For simplicity, 500 out of the 1,000 null model simulations were randomly selected and  plotted. The associated p-value for Kendall's W is shown with a solid horizontal line. Data from agreement analysis of SMH projections.")
}
```


```{r fig-s25-38, fig.height = 8, fig.cap = plt_cap_null, results="asis"}
for(i in plt_list_null){
  print(
      i
    )
    cat('\n\n')
}
```

```{r all-SMH-results}
plt_list_all <- list()
plt_cap_all <- list()
counter <- 1
for(i in unique(SMH_agreement$quantile)){
  plt_list_all[[counter]] <- ggplot(data = SMH_agreement[quantile == i][,horiz := horiz + 3], 
         aes(x = icc_a, y = kendall_w, color = as.factor(round)))+ 
    geom_point(size = 0.7, alpha = 0.3) +
    facet_grid(cols = vars(round), 
               rows = vars(horiz), 
               labeller = labeller(round = round_labs_simp, 
                                   horiz = horiz_labs)) + 
    scale_x_continuous(breaks = c(0,1),
                       minor_breaks = c(0.5),
                       limits = c(0,1),
                       #expand = c(0,0), 
                       name = "agreement between projection magnitude\n(intraclass correlation coefficient)") +
    scale_y_continuous(breaks = c(0,1),
                       minor_breaks = c(0.5),
                       #expand = c(0,0), 
                       name = "agreement between projection ranks\n(Kendall's W)") + 
    theme_bw(base_size = sz-1) + 
    theme(legend.position = "none",
          strip.background = element_blank())
  plt_cap_all[[counter]] <- paste0("Agreement between projection magnitude and ranks across evaluated SMH rounds (columns) and SMH projection horizons (rows) for SMH Q", i*100, ". Agreement between projection magnitude is measured by intraclass correlation coefficient, and agreement between scenario ranks is measured by Kendall’s W. Each point represents results for a set of projections from a single round, target, location, week. Maximum projection horizon is shown for each round, but horizon varies by round so not all hoirzons are available for all rounds. Data from agreement analysis of SMH projections.")
  counter <- counter + 1
}
```

```{r fig-s39-42, fig.cap = plt_cap_all, results="asis"}
for(i in plt_list_all){
  print(
      i
    )
    cat('\n\n')
}
```

```{r fig-s43, fig.height = 3, fig.cap = "Comparison of intraclass correlation coefficient (ICC) and Kendall’s W between quantiles. Each metric was assessed on the projected median, as well as Q25 and Q75. The left panel shows comparisons between Q25 and Q50, and the right panel shows comparisons between Q75 and Q50. Each point represents one projection  (for a single round, location). Data from agreement analysis of SMH projections."}
p1 <- SMH_agreement %>%
  .[, quantile_txt := paste0("Q", quantile*100)] %>%
  data.table::dcast(round + target + target_end_date + horiz + location ~ quantile_txt, value.var = c("icc_a", "kendall_w")) %>% 
  ggplot(aes(x = icc_a_Q75 - icc_a_Q50, y = kendall_w_Q75-kendall_w_Q50)) +
  geom_hline(aes(yintercept = 0)) + 
  geom_vline(aes(xintercept = 0)) +
  geom_point(size = 1.5, alpha = 0.2) + 
  scale_x_continuous(name = "ICC (Q75) - ICC (Q50)", 
                     limits = c(-1,1)*0.4) +
  scale_y_continuous(name = "Kendall W (Q75) - Kendall W (Q50)", 
                     limits = c(-1,1)*0.4) +
  theme_bw(base_size = sz) + 
  theme(panel.grid = element_blank())
p2 <- SMH_agreement %>%
  .[, quantile_txt := paste0("Q", quantile*100)] %>%
  data.table::dcast(round + target + target_end_date + horiz + location ~ quantile_txt, value.var = c("icc_a", "kendall_w")) %>% 
  ggplot(aes(x = icc_a_Q25 - icc_a_Q50, y = kendall_w_Q25-kendall_w_Q50)) +
  geom_hline(aes(yintercept = 0)) + 
  geom_vline(aes(xintercept = 0)) +
  geom_point(size = 1.5, alpha = 0.2) + 
  scale_x_continuous(name = "ICC (Q25) - ICC (Q50)", 
                     limits = c(-1,1)*0.4) +
  scale_y_continuous(name = "Kendall W (Q25) - Kendall W (Q50)", 
                     limits = c(-1,1)*0.4) +
  theme_bw(base_size = sz) + 
  theme(panel.grid = element_blank())
plot_grid(p2, p1, nrow = 1)
```